# Generated by Django 6.0.3 on 2026-03-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sulg',
            new_name='slug',
        ),
    ]
